Web/Models/ErrorViewModel.cs
using System;

namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Models/PersonViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Model.Models;

namespace Web.Models
{
    public class PersonViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [DisplayName("Nombre")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [DisplayName("Fecha de nacimiento")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime BirthDate { get; set; }

        public IEnumerable<Person> Persons { get; set; }
    }
}

Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SecuritySGD.Controllers;
using SecuritySGD.DataLayer;
using SecuritySGD.Entities;
using SecuritySGD.Services;
using Service.Utils;

namespace Web.Controllers
{
    public class AccountController : SecurityController
    {
        private readonly SecurityDbContext _securityContext;

        public AccountController(IAuthService authService, ITokenStoreService tokenStoreService, SecurityDbContext context) : base(authService, tokenStoreService, context)
        {
            _securityContext = context;
        }

        public override void AfterLogin(UserModel user)
        {
            var gc = new GlobalConfig
            {
                Nombre = user.DisplayName
            };
            user.Data = gc;
        }
    }
}

Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Controllers/PersonController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Model.Models;
using SecuritySGD.Utils;
using Service;
using Service.Utils;
using Web.Models;
using Web.Utils;

namespace Web.Controllers
{
    public class PersonController : Controller//: SecurityController<PersonService>
    {
        private readonly PersonService _personService;

        public PersonController(PersonService personService)// : base(personService, "PERSONA")
        {
            _personService = personService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Save()
        {
            var newPerson = new PersonViewModel
            {
                BirthDate = DateTime.Today
            };
            return View(newPerson);
        }
        
        public IActionResult Save(PersonViewModel model)
        {
            var person = model.GetModel(new Person());

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            _personService.SavePerson(person);
            _personService.SaveChanges();

            var persons = _personService.GetPersons();
            model.Persons = persons;

            return RedirectToAction("Index");
        }
        
        public IActionResult Edit(PersonViewModel model)
        {
            return View("Save", model);
        }
        
        public IActionResult Delete(PersonViewModel model)
        {

            var person = model.GetModel(new Person());

            _personService.DeletePerson(person);
            _personService.SaveChanges();

            var persons = _personService.GetPersons();
            model.Persons = persons;

            return RedirectToAction("Index");
        }
    }

    public class PersonApiController : SecurityController<PersonService>
    {
        private readonly PersonService _personService;

        public PersonApiController(PersonService personService) : base(personService, "PERSON")
        {
            _personService = personService;
        }

        [HttpGet]
        [Route("[action]")]
        [CustomAuthorize(CrudAction.Read)]
        public IDataResult GetPersons()
        {
            try
            {
                return new CustomResult(_personService.GetPersons());
            }
            catch (Exception e)
            {
                throw new ExceptionResult(e);
            }
        }
    }
}

Web/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Filters;
using Newtonsoft.Json;
using Security.Controllers;
using SecuritySGD.Controllers;
using Service;
using Service.Utils;

namespace Web.Controllers
{
    public class SecurityController<T> : BaseController where T : SecurityService
    {
        private readonly T _service;

        public SecurityController(T service, string formName) : base(formName)
        {
            this._service = service;
        }

        public GlobalConfig GlobalConfig { get; set; }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            var gc = JsonConvert.DeserializeObject<GlobalConfig>(AuthUser.Data.ToString());

            GlobalConfig = gc;
            _service.GlobalConfig = GlobalConfig;
        }
    }
}

Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Boostrap 4! :D</h1>

    <p>Y dependencias de JQuery</p>

Web/Views/Person/Index.cshtml
@{
    ViewData["Title"] = "Personas";
}
<div id="app">
    <h2>Personas</h2>
    <br />
    <div class="row">
        <div class="col-sm-3">
            @*@Html.ActionLink("Nuevo registro", "Save", "Person", null, new { @class="btn btn-success" })*@
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm">
            <table class="table table-sm table-striped table-hover">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Fecha de nacimiento</th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="person in Persons">
                    <td>{{ person.Id }}</td>
                    <td>{{ person.Name }}</td>
                    <td>{{ person.BirthDate }}</td>
                    @*<td>
                        @Html.ActionLink("Editar", "Edit", "Person", person, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Eliminar", "Delete", "Person", @item, new { @class = "btn btn-danger" })
                    </td>*@
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script src="~/js/axios.js"></script>
<script src="~/js/vue.js"></script>
<script src="~/js/urlConfig.js"></script>
<script src="~/js/Person/index.js"></script>

Web/Views/Person/Save.cshtml
@model Web.Models.PersonViewModel
@{
    ViewData["Title"] = "Save";
}

<h2>Save</h2>
<br />
<form asp-action="Save" method="post">
    <div class="row">
        @Html.HiddenFor(x => x.Id)
        <div class="col-sm-4">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name"></span>
        </div>
        <div class="col-sm-4">
            <label asp-for="BirthDate"></label>
            <input value="@Model.BirthDate.ToString("yyyy-MM-dd")" asp-for="BirthDate" class="form-control"/>
            <span asp-validation-for="BirthDate"></span>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm">
            <button class="btn btn-success">Guardar</button>
        </div>
    </div>
</form>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - App</title>
    
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse mx-5" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home<span class="sr-only">(current)</span></a>
                    <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="About">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Person" asp-action="Index">Person</a>
                </li>
            </ul>
            @*@Html.Partial("_LoginPartial")*@
        </div>
    </nav>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>

    <footer class="footer container-fluid">
        <span class="text-muted">&copy MOPC - Ministerio de Obras Públicas y Comunicaciones</span>
    </footer>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                crossorigin="anonymous">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous">
        </script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>